# =========================================================
# # 🔒 SISTEM ANTIFURT ȘI VERIFICARE INTEGRITATE COD
# =========================================================
SEMNATURA_OBLIGATORIE = "IULIAN_ICHIM_UNGUREANU"
try:
    with open(__file__, "r", encoding="utf-8") as f:
        if "IULIAN_ICHIM_UNGUREANU" not in f.read():
            import sys
            sys.exit("❌ EROARE: Licență invalidă")
except Exception:
    pass

import os
import time
import threading  # 🟢 ACEASTA ESTE LINIA SALVATOARE ADĂUGATĂ!
from flask import Flask, render_template, request, jsonify
from google import genai
import pypdf
import docx
import openpyxl
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# 🔒 CREĂM COADA GLOBALĂ SECURIZATĂ NATIVĂ (Ține utilizatorii la rând)
coada_globala = threading.Lock()

PROMPTS = {
    "RO": (
        "Ești un algoritm automat de scanare textuală și un asistent digital de tip scut contractual pentru business. "
        "NU ești avocat și NU oferi consultanță juridică. Analizează textul primit și identifică riscurile comerciale evidente. "
        "ATENȚIE: Folosește un limbaj extrem de simplu, clar și pe înțelesul unui om fără studii sau fără experiență (ca pentru cineva cu 4 clase). "
        "Evită cuvintele complicate de avocat și explică capcanele prin exemple băbești. "
        "Structurează rezultatul în ROMÂNĂ astfel: 1. Nume Risc Comercial (scris simplu), 2. Clauză originală, "
        "3. Traducere pe înțelesul tuturor (explicat super simplu), 4. De ce este o capcană periculoasă (ce poți păți/cum poți pierde bani), "
        "5. Idee simplă cum să ceri modificarea ei."
    ),
    "EN": (
        "You are an automated text scanning algorithm and a digital contract shield assistant for business. "
        "You are NOT a lawyer and you DO NOT provide legal advice. Analyze the text and identify obvious commercial risks. "
        "ATTENTION: Use an extremely simple, clear language that anyone can understand, avoiding complex legal jargon. "
        "Explain the traps using everyday, simple examples. Structure the report in ENGLISH: "
        "1. Commercial Risk Name (plain language), 2. Original Clause, 3. Super Simple Translation (plain terms), "
        "4. Why it is a dangerous trap (how you can lose money/get hurt), 5. Simple idea on how to ask for a change."
    )
}

DISCLAIMERS = {
    "RO": (
        "⚠️ NOTĂ IMPORTANTĂ DE SIGURANȚĂ JURIDICĂ:\n"
        "Acest raport este generat în mod automat de un algoritm bazat pe inteligență artificială și are un scop pur educativ, informativ și de orientare comercială generală. "
        "Prezentele puncte reprezintă o opinie algoritmică strict orientativă și NU constituie consultanță juridică autorizată. "
        "Această platformă nu înlocuiește sub nicio formă un specialist în drept.\n\n"
        "Pentru decizii contractuale oficiale, sfaturi de specialitate și o expertiză legală autorizată, vă rugăm și vă recomandăm insistent să consultați o casă de avocatură autorizată sau un cabinet de avocatură înscris în Barou.\n\n"
        "------------------------------------------------------------------------------------------------------------------------\n\n"
    ),
    "EN": (
        "⚠️ IMPORTANT LEGAL DISCLAIMER:\n"
        "This report is automatically generated by an AI algorithm and is intended strictly for educational, informational, and general business guidance purposes. "
        "These points represent a strictly indicative algorithmic opinion and DO NOT constitute authorized legal advice. "
        "This platform does not replace a legal professional.\n\n"
        "For official contractual decisions, professional advice, and authorized legal expertise, please and we strongly advise you to consult an authorized law firm or a licensed attorney.\n\n"
        "------------------------------------------------------------------------------------------------------------------------\n\n"
    )
}

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/terms')
def terms():
    return render_template('termeni.html')

@app.route('/privacy')
def privacy():
    return render_template('politica.html')

@app.route('/api/analizeaza', methods=['POST'])
def api_analizeaza():
    text_manual = request.form.get('contract', '')
    limba_cod = request.form.get('lang', 'en').upper()
    user_key = request.form.get('key', '').strip()
    
    if not user_key:
        return jsonify({'rezultat': '❌ Error: Missing Gemini API Key.' if limba_cod == 'EN' else '❌ Eroare: Lipsă cheie Gemini API.'})

    contract_final_text = ""

    if 'file' in request.files:
        uploaded_file = request.files['file']
        if uploaded_file and uploaded_file.filename != '':
            nm_f = uploaded_file.filename.lower()
            try:
                if ".pdf" in nm_f:
                    contract_final_text = "".join([p.extract_text() for p in pypdf.PdfReader(uploaded_file).pages])
                elif ".docx" in nm_f:
                    doc = docx.Document(uploaded_file)
                    contract_final_text = "\n".join([pr.text for pr in doc.paragraphs])
                elif ".xlsx" in nm_f:
                    wb = openpyxl.load_workbook(uploaded_file, data_only=True)
                    linii_excel = []
                    for sheet in wb.worksheets:
                        for row in sheet.iter_rows(values_only=True):
                            rand_text = " | ".join([str(cell) for cell in row if cell is not None])
                            if rand_text.strip(): linii_excel.append(rand_text)
                    contract_final_text = "\n".join(linii_excel)
                elif ".txt" in nm_f:
                    contract_final_text = uploaded_file.read().decode("utf-8")
            except Exception as e:
                return jsonify({'rezultat': f"Error reading file: {str(e)}"})

    if text_manual.strip():
        contract_final_text = text_manual

    if not contract_final_text.strip():
        return jsonify({'rezultat': 'Please paste text or upload a document.' if limba_cod == 'EN' else 'Te rugăm să introduci text sau să încarci un document.'})

    # --- INTEGRAREA SISTEMULUI DE COADĂ GLOBALĂ CU ALINIERE PERFECTĂ ---
    try:
        client = genai.Client(api_key=user_key)
        prompt_instructiune = PROMPTS.get(limba_cod, PROMPTS["EN"])
        response = None
        
        # Blocăm procesarea consecutivă aici (Oamenii așteaptă la rând în fundal)
        with coada_globala:
            for incercare in range(3):
                try:
                    response = client.models.generate_content(
                        model="gemini-2.5-flash", 
                        contents=f"{prompt_instructiune}\n\n{contract_final_text}"
                    )
                    break
                except Exception as ex:
                    if "503" in str(ex) and incercare < 2:
                        time.sleep(1)
                        continue
                    raise ex
                
        if response:
            text_disclaimer_protectie = DISCLAIMERS.get(limba_cod, DISCLAIMERS["EN"])
            return jsonify({'rezultat': text_disclaimer_protectie + response.text})
        else:
            return jsonify({'rezultat': 'No response from AI.'})
            
    except Exception as e:
        return jsonify({'rezultat': f"❌ AI Error: {str(e)}"})

@app.route('/robots.txt')
def robots():
    response = Flask.response_class(
        response="User-agent: *\nAllow: /",
        status=200,
        mimetype='text/plain'
    )
    # Forțăm eliminarea blocajului la nivel de header HTTP pentru ambele domenii
    response.headers['X-Robots-Tag'] = 'all'
    return response

@app.route('/ads.txt')
def ads_txt():
    # Returnează textul tău oficial cerut de Google AdSense
    continut_ads = "google.com, pub-3528838516008000, DIRECT, f08c47fec0942fa0"
    return continut_ads, 200, {'Content-Type': 'text/plain', 'X-Robots-Tag': 'all'}
    
@app.route('/api/trezire', methods=['GET'])
def api_trezire():
    # 1. Forțăm procesorul să ruleze o buclă de calcul pentru a activa resursele serverului
    simulare_calcul = sum(i * i for i in range(5000))
    
    # 2. Simulăm o mini-analiză de text în Python pentru a menține modulele în memorie
    text_fictiv = "This is a dummy contract clause designed to keep the full Python backend engine warm and prevent deep sleep."
    numar_cuvinte = len(text_fictiv.split())
    
    # 3. Returnăm răspunsul complet, inclusiv timestamp-ul tău original
    return jsonify({
        'status': 'Backend is awake and fully active', 
        'timestamp': time.time(),
        'engine_check': f'Processed {numar_cuvinte} dummy words successfully.',
        'calc_checksum': simulare_calcul
    })


if __name__ == '__main__':
    app.run(debug=True, port=5000)
